#######################
# Theme Customization #
#######################

title: ephos # used in <title> tag & site header
author: Rob Pleau # used in a <meta> tag & /feed.xml
description: > # used in a <meta> tag & /feed.xml
  Ramblings from a nerd passionate about technology and coding.
slogan: â¤ Automation # used in site header, beside title
#avatar: /images/avatar.png
avatar: https://avatars3.githubusercontent.com/u/14333618?v=3&s=460 # used as portrait in site header
#banner: /images/mountains.svg # used as background in site header
banner: /images/banner.svg
url: https://ephos.github.io/ # used by plugins to generate feed.xml and sitemap.xml
baseurl: '' # prepended to all absolute filepaths
repo: https://github.com/ephos/ephos.github.io # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /images/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /images/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/ephos
    icon: /images/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Me
    icon: /images/icons.svg#portfolio
    url: /about
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: rj.pleau       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /images/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: PowerShell Summit 2018
    teaser: My "Creating PowerShell Projects and More with Plaster" Demo
    url: https://github.com/ephos/PSSummit2018-Plaster
    role: Creator
    category: PowerShell

###########
# Plugins #
###########

google_analytics: UA-106214312-1

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
